org: sickles # Your organization name when testing
app: s3-lambda
service: api
provider:
  name: aws
  runtime: nodejs20.x
  environment:
    OTEL_SERVICE_NAME: s3-lambda
    OTEL_RESOURCE_ATTRIBUTES: "env.stage=aws-dev"
    OTEL_EXPORTER_OTLP_ENDPOINT: "https://api.honeycomb.io:443"
    OTEL_EXPORTER_OTLP_HEADERS: "x-honeycomb-team=${env:HONEYCOMB_API_KEY}"
functions:
  webhook:
    handler: src/putObject.webhook
    events:
      - http:
          method: GET
          path: /
  getObjectJS:
    handler: src/getObjectJS.handler
    events:
      - http:
          path: get-object-js
          method: get

  getObjectTS:
    handler: src/getObjectTS.handler
    events:
      - http:
          path: get-object-ts
          method: get
  listObjects:
    handler: src/listObjects.handler
    events:
      - http:
          path: list-objects
          method: get
plugins:
  - serverless-offline
  - serverless-s3-local
custom:
  serverless-offline:
      httpPort: 4000
  s3:
    host: localhost
    directory: ./s3-local
resources:
  Resources:
    NewResource:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: local-bucket
build:
  esbuild:
    # Enable or Disable bundling the function code and dependencies. (Default: true)
    bundle: true
    # Enable minifying function code. (Default: false)
    minify: false
    # NPM packages to not be bundled. Glob patterns are supported here.
    # THIS DID NOTHING
    # nodeModules:
    #   - '@aws-sdk/client-s3' 
    external:
      - '@aws-sdk/client-s3'
      # - '@aws-sdk/client-dynamodb'
    # NPM packages to not be bundled, as well as not included in node_modules
    # in the zip file uploaded to Lambda. By default this will be set to aws-sdk
    # if the runtime is set to nodejs16.x or lower or set to @aws-sdk/* if set to nodejs18.x or higher.
    # Glob patterns are supported here.
    exclude:
      - '@aws-sdk/*'
    #   - '!@aws-sdk/client-bedrock-runtime'
    # The packages config, this can be set to override the behavior of external
    # If this is set then all dependencies will be treated as external and not bundled.
    # packages: external
    # By default Framework will attempt to build and package all functions concurrently.
    # This property can bet set to a different number if you wish to limit the
    # concurrency of those operations.
    buildConcurrency: 3
    # Enable or configure sourcemaps, can be set to true or to an object with further configuration.
    sourcemap:
      # The sourcemap type to use, options are (inline, linked, or external)
      type: linked
      # Whether to set the NODE_OPTIONS on functions to enable sourcemaps on Lambda
      setNodeOptions: true